#ifndef HELPERS
#define HELPERS
#ifdef LOCAL_TEST_ENVIRONMENT
#include "own_test_math.h"
#else
#include "stm32f30x.h"
#include "arm_math.h"
#endif

#define MIN_INCL_ACC 1.0

// vector methods
typedef struct {
    uint32_t t;
    float x;
    float y;
    float z;
} fVector3;

typedef struct {
    uint8_t motor_initialized; // If enabled than the timers generate signals towards the ESC
    uint8_t sensor_streaming;  // If enabled than new measurements generated by the sensors are send automatically
} STM_OptionsStruct;

#ifndef LOCAL_TEST_ENVIRONMENT
void Init_Helpers();
void Delay(__IO uint32_t nTime);
void LedByte(uint8_t info);
void LedAngle(float angle);
void Inclination2Led(fVector3* accData);
#endif

// Time since startup in ms
uint32_t time_since_startup;

void add(fVector3* a, fVector3 b);
void sub(fVector3* a, fVector3 b);

#endif
